version: 2.1

jobs:
  say-hello:
    docker:
      - image: cimg/base:current

    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"
          
  testflight:
    macos:
      xcode: 14.2.0
    steps:
      - checkout
      - ruby/setup:
          version: '3.0.2'  # 사용하려는 Ruby 버전 지정 (필요에 따라 조정)
      - run:
          name: Navigate to App-Fastlane directory
          command: cd App-Fastlane
      - run:
          name: Print current directory and list files
          command: |
            pwd
            ls -la
      - run:
          name: Bundle install
          command: |
            cd App-Fastlane
            bundle install
      - run:
          name: Fastlane TestFlight
          command: |
            cd App-Fastlane
            bundle exec fastlane tf

workflows:
  say-hello-workflow:
    jobs:
      - say-hello
  
  build-and-deploy:
    jobs:
      - testflight:
          filters:
            branches:
              only: main
