version: 2.1

orbs:
  ruby: circleci/ruby@2.0.1

jobs:
  say-hello:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"
          
  testflight:
    macos:
      xcode: 14.2.0
    steps:
      - checkout
      - ruby/install-deps  # Ruby orb을 사용하여 의존성 설치
      - run:
          name: Navigate to App-Fastlane directory and run commands
          command: |
            cd App-Fastlane
            pwd
            ls -la
            bundle exec fastlane tf

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - say-hello
      - testflight:
          filters:
            branches:
              only: main
