version: 2.1

orbs:
  ruby: circleci/ruby@1.2.0

jobs:
  say-hello:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"
          
  testflight:
    macos:
      xcode: 14.2.0
    steps:
      - checkout
      - ruby/setup:
          version: '3.0.2'  # 사용하려는 Ruby 버전 지정 (필요에 따라 조정)
      - run:
          name: Navigate to App-Fastlane directory and run commands
          command: |
            cd App-Fastlane
            pwd
            ls -la
            bundle install
            bundle exec fastlane tf

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - say-hello
      - testflight:
          filters:
            branches:
              only: main
