version: 2.1

jobs:
  testflight:
    macos:
      xcode: 14.2.0
    environment:
      FL_OUTPUT_DIR: output
    steps:
      - checkout
      - run: bundle install
      - run:
          name: Fastlane TestFlight
          command: bundle exec fastlane tf
      - store_artifacts:
          path: output

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - testflight:
          filters:
            branches:
              only: master
