version: 2.1

jobs:
  say-hello:
    docker:
      - image: cimg/base:current

    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"
          
  testflight:
    macos:
      xcode: 14.2.0
    environment:
      FL_OUTPUT_DIR: output
    steps:
      - checkout
      - run: bundle install
      - run:
          name: Fastlane TestFlight
          command: bundle exec fastlane tf
      - store_artifacts:
          path: output

workflows:
  say-hello-workflow:
    jobs:
      - say-hello
  
  build-and-deploy:
    jobs:
      - testflight:
          filters:
            branches:
              only: main
